### PR TITLE
Support for Caddyfile

### PR DESCRIPTION
**Pull request by zachgalvin**
With version 2.8.0 of Caddy, the Caddyfile adapter will have the ability to load client_auth verifier modules with [PR 6022](https://github.com/caddyserver/caddy/pull/6022), so I was hoping to add the below code to allow this module to work with the Caddyfile adapter as well. 

Open issue on this here: #2 

Not sure if there are other thoughts for how to do this, but the below works well!

### CODE REVIEW

**Comment by Gr33nbl00d** [comment]
Oh that are great news i didnt know that this was added in caddy. I would have added this otherwise already but problem was that it required changes in caddy which could potentially cause backward incompatibility changes. I try to find some time in the next week to test and review this pr. Thanks

**Comment by zachgalvin** [comment]
No problem! That sounds great!

I did leave a debug line in the code, so it probably makes sense to remove that line and remove the log module import as well since that's the only time we use it:
log.Printf("key: %v", key)

**Comment by Gr33nbl00d** [comment]
I did some quick review. But i need to do some further tests and refactorings (too many loops in one method) + additions + documentation.
So i need some more days

**Comment by zachgalvin** [comment]
All good. That sounds good. Thanks!

**Comment by Gr33nbl00d** [comment]
Funny it looks like they broke your pull request a few weeks after your merge somehow in caddy with a refactoring.
https://github.com/caddyserver/caddy/pull/5784

I already commented and could repair it locally for implementation.

**Comment by francislavoie** [comment]
Small nit: I'd call the new file `caddyfile.go`, not `caddyUnmarshal.go`.

**Comment by Gr33nbl00d** [comment]
> Small nit: I'd call the new file `caddyfile.go`, not `caddyUnmarshal.go`.

Thanks for the suggestion i will do so. Very welcome :)

**Comment by zachgalvin** [comment]
Hey @Gr33nbl00d, do you think you will have time to look at this again now that they re-added the code from my pull request? https://github.com/caddyserver/caddy/pull/6127

**Pull request merged**
